substitutions:
  _SERVICE_NAME: sfkit-website
  _FRONTEND_SERVICE_NAME: sfkit-react
  _GCR_HOSTNAME: us.gcr.io
  _CORS_ORIGINS: ""
  _DATABASE_NAME: sfkit
  _DATABASE_REGION: us-central1
  _STORAGE_REGION: us-central1
  _RESULTS_BUCKET: ${PROJECT_ID}-sfkit
  _TF_STATE_BUCKET: ${PROJECT_ID}-terraform
  _FLASK_DEBUG: "0"
  _OIDC_AUDIENCE: "" # Typically, OAuth client ID
  _OIDC_JWKS_URL: https://www.googleapis.com/oauth2/v3/certs
  _IMAGE: ${_GCR_HOSTNAME}/${PROJECT_ID}/${_SERVICE_NAME}
  _SFKIT_PROXY_ARGS: "-v"
  _TF_AUTO_APPROVE: "false"

options:
  logging: CLOUD_LOGGING_ONLY
  automapSubstitutions: true

steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    script: >-
      docker buildx create --use --driver docker-container &&
      [ "$_TF_AUTO_APPROVE" = "false" ] ||
      docker buildx build --push -t $_IMAGE:$SHORT_SHA
      --cache-from type=registry,ref=$_IMAGE:cache
      --cache-to type=registry,ref=$_IMAGE:cache,mode=max
      --build-arg APP_VERSION=$SHORT_SHA
      --build-arg BUILD_VERSION=$SHORT_SHA .

  - id: tf-init
    name: hashicorp/terraform
    waitFor: ["-"]
    dir: terraform
    args:
      - init
      - -backend-config=bucket=$_TF_STATE_BUCKET

  - name: hashicorp/terraform
    dir: terraform
    entrypoint: sh
    args:
      - -c
      - |
        set -e
        if [ "$_TF_AUTO_APPROVE" = "true" ]; then
          CMD="apply -auto-approve"
        else
          CMD="plan"
        fi
        terraform $$CMD \
          "-var=project_id=$PROJECT_ID" \
          "-var=artifact_repository=$_GCR_HOSTNAME" \
          "-var=image=$_IMAGE:$SHORT_SHA" \
          "-var=cors_origins=$_CORS_ORIGINS" \
          "-var=service_name=$_SERVICE_NAME" \
          "-var=database_name=$_DATABASE_NAME" \
          "-var=database_region=$_DATABASE_REGION" \
          "-var=storage_region=$_STORAGE_REGION" \
          "-var=results_bucket=$_RESULTS_BUCKET" \
          "-var=flask_debug=$_FLASK_DEBUG" \
          "-var=oidc_audience=$_OIDC_AUDIENCE" \
          "-var=oidc_jwks_url=$_OIDC_JWKS_URL" \
          "-var=sfkit_proxy_args=$_SFKIT_PROXY_ARGS" \
          "-var=frontend_service_name=$_FRONTEND_SERVICE_NAME"
