SERVER_GCP_PROJECT = "broad-cho-priv1"
ZONE = "us-central1-a"
REGION = "us-central1"
NETWORK_NAME = "secure-gwas"
SUBNET_NAME = "secure-gwas-subnet"
INSTANCE_NAME_ROOT = "secure-gwas"
BUCKET_NAME = "broad-cho-priv1-secure-gwas-data"
